sudo: required
services:
  - docker

before_install:
  - docker --version

jobs:
  include:
    - stage: build
      script:
        # Build Docker images for each container
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker build -t udagram-api-user ./udagram-api-user
        - docker build -t udagram-frontend ./udagram-frontend

    - stage: deploy
      script:
        # Tag and push Docker images for each container to Docker Hub
        - docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:v1
        - docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:v1
        - docker tag udagram-frontend "$DOCKER_USERNAME"/udagram-frontend:v1

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push "$DOCKER_USERNAME"/udagram-api-feed:v1
        - docker push "$DOCKER_USERNAME"/udagram-api-user:v1
        - docker push "$DOCKER_USERNAME"/udagram-frontend:v1
