sudo: required
services:
  - docker

stages:
  - build
  - tag

before_install:
  - docker --version

jobs:
  include:
    - stage: build
      script:
        # Build Docker images
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker build -t udagram-api-user ./udagram-api-user
        - docker build -t udagram-frontend ./udagram-frontend
        - docker build -t udagram-reverseproxy ./udagram-reverseproxy

    - stage: tag
      script:
        # Tag Docker images
        - docker tag udagram-api-feed:latest hungvm1/udagram-api-feed:v1
        - docker tag udagram-api-user:latest hungvm1/udagram-api-user:v1
        - docker tag udagram-frontend:latest hungvm1/udagram-frontend:v1
        - docker tag udagram-reverseproxy:latest hungvm1/udagram-reverseproxy:v1

after_success:
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push Docker images to Docker Hub with tag v1
  - docker push hungvm1/udagram-api-feed:v1
  - docker push hungvm1/udagram-api-user:v1
  - docker push hungvm1/udagram-frontend:v1
  - docker push hungvm1/udagram-reverseproxy:v1
