version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: "$DOCKER_USERNAME"/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: "$DOCKER_USERNAME"/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: "$DOCKER_USERNAME"/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: "$DOCKER_USERNAME"/udagram-frontend:local